language: java

jdk:
- oraclejdk8

branches:
  only:
    - 1.7.10
    - master
    
before_install:
- chmod +x ./gradlew
- chmod +x ./gradlew assemble

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
  - "checksums.txt"
  - "build/libs/Dynamic_Surroundings-*-unofficial.jar"
  - "build/packages/Dynamic_Surroundings-*-unofficial-*.jar"
  skip_cleanup: true
  on:
    tags: true
