language: java
sudo: false
jdk:
- oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:

before_install:
- git submodule update --init

install: travis_wait 100

script:
- travis_wait 100 gradle check
- ls -la build/libs
- ls -la build/packages

# Deploy the artifacts back to GitHub
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
  - "build/libs/Dynamic_Surroundings-*-unofficial.jar"
  - "build/packages/Dynamic_Surroundings-*-unofficial-*.jar"
  skip_cleanup: true
  on:
    tags: true

